/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.mycompany.java_assignment;

import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author bisma
 */
public class Menu extends javax.swing.JPanel {

    /**
     * Creates new form Menu
     */
    Customer cs;
    UserSession user;
    public Menu() {
        initComponents();
        order_detail_panel.setVisible(false);

        DefaultTableModel tableModel = (DefaultTableModel) menu_table.getModel();

        // Get selected category
        String category = Customer.getSelectedCategory();

        // Get selected restaurant ID
       String restID = Customer.getVendorIDByName(Customer.getSelectedRestaurant());

        // Display the menu based on category and restaurant ID
        if (restID != null) {
            Customer.displayMenuFromFile(category, restID, tableModel);
        } else {
            JOptionPane.showMessageDialog(null, "Error: Restaurant ID not found.");
        }
}


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField1 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        menu_table = new javax.swing.JTable();
        order_detail_panel = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        deli = new javax.swing.JRadioButton();
        tak = new javax.swing.JRadioButton();
        din = new javax.swing.JRadioButton();
        jLabel3 = new javax.swing.JLabel();
        addresstxt = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        fees = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        paybtn = new javax.swing.JButton();
        totalPrice = new javax.swing.JButton();
        numItems = new javax.swing.JLabel();
        totalamount = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();

        jTextField1.setText("jTextField1");

        setBackground(new java.awt.Color(255, 255, 255));
        setForeground(new java.awt.Color(0, 0, 0));
        setName("menu"); // NOI18N
        setPreferredSize(new java.awt.Dimension(752, 521));

        jLabel1.setFont(new java.awt.Font("Arial Black", 0, 18)); // NOI18N
        jLabel1.setText("Menu");

        menu_table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Item Name ", "Discription", "Price ", "Number of Item"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.Integer.class, java.lang.Integer.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        menu_table.setAutoscrolls(false);
        menu_table.setName("menu_table"); // NOI18N
        jScrollPane1.setViewportView(menu_table);

        order_detail_panel.setBorder(javax.swing.BorderFactory.createTitledBorder("Order Details"));
        order_detail_panel.setName("order_detail_panel"); // NOI18N

        jLabel2.setText("Order Type");

        deli.setText("Delivery");
        deli.setName("delivary_rb"); // NOI18N

        tak.setText("Takeaway");
        tak.setName("takeaway_rb"); // NOI18N

        din.setText("Dine-In");
        din.setName("dine_in_rb"); // NOI18N

        jLabel3.setText("Address");

        addresstxt.setName("address_textfield"); // NOI18N

        jLabel4.setText("Number of Item  :");

        fees.setText("Delivery Fee : RM0");
        fees.setName("delivary_fee_lbl"); // NOI18N

        jLabel6.setText("Total Amount : ");

        paybtn.setText("Pay");
        paybtn.setEnabled(false);
        paybtn.setName("payorder_button"); // NOI18N
        paybtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                paybtnActionPerformed(evt);
            }
        });

        totalPrice.setBackground(new java.awt.Color(0, 0, 0));
        totalPrice.setFont(new java.awt.Font("Arial Black", 1, 12)); // NOI18N
        totalPrice.setForeground(new java.awt.Color(255, 255, 255));
        totalPrice.setText("Generate Bill");
        totalPrice.setName("generate_bill_button"); // NOI18N
        totalPrice.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                totalPriceActionPerformed(evt);
            }
        });

        numItems.setText("_____");
        numItems.setName("number_of_item_lbl"); // NOI18N

        totalamount.setText("0");
        totalamount.setName("total_amount_lbl"); // NOI18N

        javax.swing.GroupLayout order_detail_panelLayout = new javax.swing.GroupLayout(order_detail_panel);
        order_detail_panel.setLayout(order_detail_panelLayout);
        order_detail_panelLayout.setHorizontalGroup(
            order_detail_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(order_detail_panelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(order_detail_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(jLabel2)
                    .addGroup(order_detail_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(addresstxt, javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, order_detail_panelLayout.createSequentialGroup()
                            .addComponent(deli)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(tak)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(din))))
                .addGap(18, 29, Short.MAX_VALUE)
                .addGroup(order_detail_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, order_detail_panelLayout.createSequentialGroup()
                        .addComponent(paybtn)
                        .addGap(18, 18, 18)
                        .addComponent(totalPrice)
                        .addGap(36, 36, 36))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, order_detail_panelLayout.createSequentialGroup()
                        .addGroup(order_detail_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(order_detail_panelLayout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(numItems))
                            .addComponent(fees)
                            .addGroup(order_detail_panelLayout.createSequentialGroup()
                                .addComponent(jLabel6)
                                .addGap(18, 18, 18)
                                .addComponent(totalamount)))
                        .addGap(111, 111, 111))))
        );
        order_detail_panelLayout.setVerticalGroup(
            order_detail_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(order_detail_panelLayout.createSequentialGroup()
                .addGroup(order_detail_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(order_detail_panelLayout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(order_detail_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(deli)
                            .addComponent(tak)
                            .addComponent(din))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(addresstxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(order_detail_panelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(order_detail_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(numItems))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(fees)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(order_detail_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(totalamount))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(order_detail_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(totalPrice)
                            .addComponent(paybtn))))
                .addContainerGap(13, Short.MAX_VALUE))
        );

        jButton1.setBackground(new java.awt.Color(0, 0, 0));
        jButton1.setFont(new java.awt.Font("Arial Black", 1, 12)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("View Rating");
        jButton1.setName("view_rating_button"); // NOI18N
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setBackground(new java.awt.Color(0, 0, 0));
        jButton2.setFont(new java.awt.Font("Arial Black", 1, 12)); // NOI18N
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setText("Order");
        jButton2.setName("order_button"); // NOI18N
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton5.setBackground(new java.awt.Color(0, 0, 0));
        jButton5.setForeground(new java.awt.Color(255, 255, 255));
        jButton5.setText("<");
        jButton5.setName("exit_to_homepage_button"); // NOI18N
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(67, 67, 67)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(241, 241, 241)
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 225, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jButton1)
                                .addGap(48, 48, 48)
                                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(158, 158, 158))
                            .addComponent(order_detail_panel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 520, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(165, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(jLabel1)
                .addGap(32, 32, 32)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2))
                .addGap(37, 37, 37)
                .addComponent(order_detail_panel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 59, Short.MAX_VALUE)
                .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(16, 16, 16))
        );

        getAccessibleContext().setAccessibleName("Menu");
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
    order_detail_panel.setVisible(true);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        View_Rating view_rating =  new View_Rating();
        cs.switchPanel(view_rating); 
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        HomePage homepage =  new HomePage();
        cs.switchPanel(homepage);
     }//GEN-LAST:event_jButton5ActionPerformed

    private void paybtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_paybtnActionPerformed
       String IDCustomer = user.getUserID(); 
        Double Balance = cs.getBalance(IDCustomer);
       Double Total = Double.valueOf(totalamount.getText());
       String Address = addresstxt.getText();
       if(Balance >= Total) {
           if(deli.isSelected()) {
                if(Address.isEmpty()) {
                    JOptionPane.showMessageDialog(null, "Write Address first");
                }
            }
           int[] selectedRows = menu_table.getSelectedRows();
           List<String> foodList = new ArrayList<>();
           int totalnum = 0;
           for (int row : selectedRows) {
              String foodItem = (String) menu_table.getValueAt(row, 0);
               int num = (int) menu_table.getValueAt(row, 3);
              foodList.add(foodItem + " "+ num+"x");
              totalnum =+ num;
           }
          String items = String.join(", ", foodList);
          String orderType = tak.isSelected() ? "Takeaway" :
                   deli.isSelected() ? "Delivery" :
                   din.isSelected() ? "Dine-in" : "No option selected";
          cs.addOrder(items, totalnum);
          menu_table.clearSelection();
          String messageNoti = "Your order has been created check order page";
          Customer.saveNotification(IDCustomer, messageNoti);
          Customer.setBalance(IDCustomer, Total);
          Customer.saveTransaction(IDCustomer, Total, "Payment Order");
       } else {
         JOptionPane.showMessageDialog(null, "You don't have enough money please recharge your wallet");  
       }
    }//GEN-LAST:event_paybtnActionPerformed

    private void totalPriceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_totalPriceActionPerformed
        if(!deli.isSelected() && !tak.isSelected() && !din.isSelected()) {
            JOptionPane.showMessageDialog(null, "Please Select Type Of Order");
        } else {
             int selectedRow = menu_table.getSelectedRow();
            if (selectedRow != -1) {
         int[] selectedRows = menu_table.getSelectedRows();
         System.out.println(selectedRows.length);
         Double total = 0.0;
         fees.setText("Delivery Fee : RM0");
         if(deli.isSelected()) {
         fees.setText("Delivery Fee : RM5");
         total += 5;
         }
         Object itemIsSelected = menu_table.getValueAt(selectedRow, 3);
               if(itemIsSelected == null) {
               JOptionPane.showMessageDialog(null, "Input how many items you want..");
              } else {
         for (int row : selectedRows) {
              String foodItem = (String) menu_table.getValueAt(row, 0); 
              Double price = (Double) menu_table.getValueAt(row, 2);
              int num = (int) menu_table.getValueAt(row, 3);
              System.out.println(price * num);
              total += price * num;
         }
        numItems.setText(selectedRows.length + "");
        totalamount.setText(total.toString());
        paybtn.setEnabled(true);
               }
           } else  {
                JOptionPane.showMessageDialog(null, "Please select an items to process.");
           }
        }
    }//GEN-LAST:event_totalPriceActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField addresstxt;
    private javax.swing.JRadioButton deli;
    private javax.swing.JRadioButton din;
    private javax.swing.JLabel fees;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTable menu_table;
    private javax.swing.JLabel numItems;
    private javax.swing.JPanel order_detail_panel;
    private javax.swing.JButton paybtn;
    private javax.swing.JRadioButton tak;
    private javax.swing.JButton totalPrice;
    private javax.swing.JLabel totalamount;
    // End of variables declaration//GEN-END:variables
}

