/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.mycompany.java_assignment;

/**
 *
 * @author bisma
 */
public class Order_in_progress extends javax.swing.JPanel {

    /**
     * Creates new form Order_in_progress
     */
    Customer cs;
    public Order_in_progress() {
        initComponents();
            cs = new Customer();
    String IDCustomer = UserSession.getUserID();
  String orderId = cs.getFirstOrderIdByCustomerId(IDCustomer);
   txtxid.setText(orderId);
   String Status = cs.getOrderStatusByCustomerId(IDCustomer);
   ststustxt.setText(Status);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        customer_id_lbl = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtxid = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        ststustxt = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));

        customer_id_lbl.setBackground(new java.awt.Color(255, 255, 255));
        customer_id_lbl.setBorder(javax.swing.BorderFactory.createTitledBorder("Tracking Your Order"));

        jLabel1.setText("Order ID : ");

        txtxid.setText("___________");
        txtxid.setName("order_id_lbl"); // NOI18N

        jLabel3.setText("Order Status : ");

        ststustxt.setText("___________");
        ststustxt.setName("order_status_lbl"); // NOI18N

        javax.swing.GroupLayout customer_id_lblLayout = new javax.swing.GroupLayout(customer_id_lbl);
        customer_id_lbl.setLayout(customer_id_lblLayout);
        customer_id_lblLayout.setHorizontalGroup(
            customer_id_lblLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, customer_id_lblLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(ststustxt)
                .addGap(113, 113, 113))
            .addGroup(customer_id_lblLayout.createSequentialGroup()
                .addGroup(customer_id_lblLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(customer_id_lblLayout.createSequentialGroup()
                        .addGap(56, 56, 56)
                        .addGroup(customer_id_lblLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel1)))
                    .addGroup(customer_id_lblLayout.createSequentialGroup()
                        .addGap(110, 110, 110)
                        .addComponent(txtxid)))
                .addContainerGap(128, Short.MAX_VALUE))
        );
        customer_id_lblLayout.setVerticalGroup(
            customer_id_lblLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(customer_id_lblLayout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtxid)
                .addGap(18, 18, 18)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ststustxt)
                .addContainerGap(27, Short.MAX_VALUE))
        );

        jLabel2.setFont(new java.awt.Font("Arial Black", 0, 18)); // NOI18N
        jLabel2.setText("Order in Progress");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(148, 148, 148)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(customer_id_lbl, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(53, 53, 53)
                        .addComponent(jLabel2)))
                .addContainerGap(211, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(81, 81, 81)
                .addComponent(jLabel2)
                .addGap(47, 47, 47)
                .addComponent(customer_id_lbl, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(91, Short.MAX_VALUE))
        );

        getAccessibleContext().setAccessibleName("Order_in_progress");
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel customer_id_lbl;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel ststustxt;
    private javax.swing.JLabel txtxid;
    // End of variables declaration//GEN-END:variables
}
