    /*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
    package com.mycompany.java_assignment;

import javax.swing.JOptionPane;

/**
 *
 * @author bisma
 */
    public class Order_completed extends javax.swing.JPanel {

    /**
     * Creates new form Order_completed
     */
    public Order_completed() {
        initComponents();
     
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        awful_rider = new javax.swing.JRadioButton();
        poor_rider = new javax.swing.JRadioButton();
        average_rider = new javax.swing.JRadioButton();
        good_rider = new javax.swing.JRadioButton();
        excellent_rider = new javax.swing.JRadioButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        awful_vendor = new javax.swing.JRadioButton();
        poor_vendor = new javax.swing.JRadioButton();
        average_vendor = new javax.swing.JRadioButton();
        good_vendor = new javax.swing.JRadioButton();
        excellent_vendor = new javax.swing.JRadioButton();
        btn = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 255, 255));
        setName(""); // NOI18N

        jLabel1.setFont(new java.awt.Font("Arial Black", 1, 18)); // NOI18N
        jLabel1.setText("Order Completed !");

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Rate your rider"));

        awful_rider.setText("Awful");
        awful_rider.setName("r_awful_rb"); // NOI18N
        awful_rider.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                awful_riderActionPerformed(evt);
            }
        });

        poor_rider.setText("Poor");
        poor_rider.setName("r_poor_rb"); // NOI18N
        poor_rider.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                poor_riderActionPerformed(evt);
            }
        });

        average_rider.setText("Average");
        average_rider.setName("r_average_rb"); // NOI18N

        good_rider.setText("Good");
        good_rider.setName("r_good_rb"); // NOI18N

        excellent_rider.setText("Excellent");
        excellent_rider.setName("r_excellent_rb"); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(awful_rider)
                            .addComponent(poor_rider)
                            .addComponent(average_rider))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(good_rider)
                            .addComponent(excellent_rider))
                        .addGap(0, 65, Short.MAX_VALUE))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(12, Short.MAX_VALUE)
                .addComponent(awful_rider)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(poor_rider)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(average_rider)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(good_rider)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(excellent_rider))
        );

        jLabel2.setFont(new java.awt.Font("Arial Black", 1, 14)); // NOI18N
        jLabel2.setText("Thank you for your order!");

        jLabel3.setText("Lets us know your thoughts by leaving a rating below.");

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder("Rate your Food"));

        awful_vendor.setText("Awful");
        awful_vendor.setName("f_awful_rb"); // NOI18N
        awful_vendor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                awful_vendorActionPerformed(evt);
            }
        });

        poor_vendor.setText("Poor");
        poor_vendor.setName("f_poor_rb"); // NOI18N
        poor_vendor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                poor_vendorActionPerformed(evt);
            }
        });

        average_vendor.setText("Average");
        average_vendor.setName("f_average_rb"); // NOI18N

        good_vendor.setText("Good");
        good_vendor.setName("f_good_rb"); // NOI18N

        excellent_vendor.setText("Excellent");
        excellent_vendor.setName("f_excellent_rb"); // NOI18N

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(awful_vendor)
                            .addComponent(poor_vendor)
                            .addComponent(average_vendor))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(good_vendor)
                            .addComponent(excellent_vendor))
                        .addGap(0, 56, Short.MAX_VALUE))))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(awful_vendor)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(poor_vendor)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(average_vendor)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(good_vendor)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(excellent_vendor)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        btn.setBackground(new java.awt.Color(0, 0, 0));
        btn.setFont(new java.awt.Font("Arial Black", 1, 12)); // NOI18N
        btn.setForeground(new java.awt.Color(255, 255, 255));
        btn.setText("Submit");
        btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(92, 92, 92)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel3)
                        .addGap(29, 29, 29))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(67, 67, 67)
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(137, 137, 137)
                        .addComponent(btn, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(78, 78, 78)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel1))))
                .addContainerGap(278, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 58, Short.MAX_VALUE)
                .addComponent(jLabel3)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btn, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(67, 67, 67))
        );

        getAccessibleContext().setAccessibleName("Order_completed");
    }// </editor-fold>//GEN-END:initComponents

    private void poor_riderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_poor_riderActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_poor_riderActionPerformed

    private void poor_vendorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_poor_vendorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_poor_vendorActionPerformed

    private void awful_riderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_awful_riderActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_awful_riderActionPerformed

    private void awful_vendorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_awful_vendorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_awful_vendorActionPerformed

    private void btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnActionPerformed
 
        JOptionPane.showMessageDialog(null, "Thank You for your time.");
        btn.setEnabled(false);
//Customer customer = new Customer(); // Create an instance of Customer
//
//        int riderRating = customer.getRiderRating(awful_rider, poor_rider, average_rider, good_rider, excellent_rider);
//        int vendorRating = customer.getVendorRating(awful_vendor, poor_vendor, average_vendor, good_vendor, excellent_vendor);
//
//        if (riderRating == -1 || vendorRating == -1) {
//            JOptionPane.showMessageDialog(null, "Please select a rating for both Rider and Vendor.");
//        } else {
//            String userID = UserSession.getUserID();  // Assuming you have a user session
//            String orderID = "123";  // Replace with actual order ID
//            String restaurant = "Restaurant Name";  // Replace with actual restaurant name
//            String reviewText = reviewTextField.getText();  // Get review text from text field
//
//            customer.saveReview(userID, orderID, restaurant, reviewText, riderRating, vendorRating);
                    }//GEN-LAST:event_btnActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton average_rider;
    private javax.swing.JRadioButton average_vendor;
    private javax.swing.JRadioButton awful_rider;
    private javax.swing.JRadioButton awful_vendor;
    private javax.swing.JButton btn;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.JRadioButton excellent_rider;
    private javax.swing.JRadioButton excellent_vendor;
    private javax.swing.JRadioButton good_rider;
    private javax.swing.JRadioButton good_vendor;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JRadioButton poor_rider;
    private javax.swing.JRadioButton poor_vendor;
    // End of variables declaration//GEN-END:variables
}
