/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.mycompany.java_assignment;

import javax.swing.JOptionPane;

/**
 *
 * @author bisma
 */
public class View_Top_Up_History extends javax.swing.JPanel {

    /**
     * Creates new form View_Recipes
     */
    Customer cs;
    public View_Top_Up_History() {
        initComponents();
        Customer c = new Customer();
        c.loadTopupHistory(tblTopupHistory);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tblTopupHistory = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        btnView = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 255, 255));
        setPreferredSize(new java.awt.Dimension(679, 484));

        jScrollPane1.setName("view_recipes_tables"); // NOI18N

        tblTopupHistory.setBackground(new java.awt.Color(255, 255, 255));
        tblTopupHistory.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Amount", "Status", "Date Sent", "Date Completed"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        tblTopupHistory.setName("view_topup_recipes_table"); // NOI18N
        jScrollPane1.setViewportView(tblTopupHistory);
        if (tblTopupHistory.getColumnModel().getColumnCount() > 0) {
            tblTopupHistory.getColumnModel().getColumn(0).setResizable(false);
        }

        jLabel1.setFont(new java.awt.Font("Arial Black", 1, 18)); // NOI18N
        jLabel1.setText("Top-Up History ");
        jLabel1.setToolTipText("");
        jLabel1.setName("topup_history_lbl"); // NOI18N

        btnView.setBackground(new java.awt.Color(0, 0, 0));
        btnView.setFont(new java.awt.Font("Arial Black", 1, 12)); // NOI18N
        btnView.setForeground(new java.awt.Color(255, 255, 255));
        btnView.setText("View Receipt");
        btnView.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnViewActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(53, 53, 53)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(191, 191, 191)
                        .addComponent(jLabel1))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 545, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(203, 203, 203)
                        .addComponent(btnView, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(81, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(53, 53, 53)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 268, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnView, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(77, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        E_Wallet e_wallet =  new E_Wallet();
        cs.switchPanel(e_wallet);
    }//GEN-LAST:event_jButton5ActionPerformed

    private void btnViewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnViewActionPerformed
    int selectedRow = tblTopupHistory.getSelectedRow();
        if (selectedRow == -1) {
        JOptionPane.showMessageDialog(this, 
            "Please select a top-up record first.", 
            "No Selection", 
            JOptionPane.WARNING_MESSAGE);
        return;
    }
    
    
    String amount = tblTopupHistory.getValueAt(selectedRow, 0).toString();
    String status = tblTopupHistory.getValueAt(selectedRow, 1).toString();
    String dateSent = tblTopupHistory.getValueAt(selectedRow, 2).toString();
    String dateCompleted = tblTopupHistory.getValueAt(selectedRow, 3).toString();
    
    String message = "Sent Data: " + dateSent + "\n" +
                     "Total Amount: " + amount + "\n" +
                     "Status: " + status + "\n" +
                     "Date Completed: " + dateCompleted;
    
    JOptionPane.showMessageDialog(this, message, "Receipt Details", JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_btnViewActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnView;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblTopupHistory;
    // End of variables declaration//GEN-END:variables
}
